// import ClientSetupContextProvider from '@/src/components/ClientSetupContextProvider';
import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Furonto',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body>
        {/* <ClientSetupContextProvider> */}
        {children}
        {/* </ClientSetupContextProvider> */}
      </body>
    </html>
  );
}
